const data = [
  {
    id: 1,
    name: "Spicy Grill",
    cuisines: ["Indian", "Barbecue"],
    image:
      "https://th.bing.com/th/id/OIP.J2LwWphLZVnb7xpMRWZjjAHaEK?rs=1&pid=ImgDetMain",
    rating: 4.5,
    time: "30 mins",
    offer: "20% off on orders above $30",
    items: [
      { id: 101, name: "Tandoori Chicken", price: 12.99 },
      { id: 111, name: "Paneer Tikka", price: 10.5 },
      { id: 112, name: "Lamb Seekh Kebab", price: 13.75 },
      { id: 113, name: "Butter Naan", price: 2.5 },
      { id: 114, name: "Chicken Biryani", price: 11.99 },
    ],
  },
  {
    id: 2,
    name: "Sushi World",
    cuisines: ["Japanese", "Seafood"],
    image:
      "https://th.bing.com/th/id/OIP.DZagOzmfIANIVh3OzqiYhgAAAA?rs=1&pid=ImgDetMain",
    rating: 4.7,
    time: "25 mins",
    offer: "Free miso soup with every order",
    items: [
      { id: 102, name: "Salmon Sushi Platter", price: 18.5 },
      { id: 115, name: "Tuna Roll", price: 14.0 },
      { id: 116, name: "Eel Nigiri", price: 13.25 },
      { id: 117, name: "Tempura Shrimp", price: 10.75 },
      { id: 118, name: "Avocado Maki", price: 8.5 },
    ],
  },
  {
    id: 3,
    name: "Pasta Palace",
    cuisines: ["Italian", "Continental"],
    image:
      "https://th.bing.com/th/id/OIP.gAHAtntCt5vxO0BipJI-LAHaGu?rs=1&pid=ImgDetMain",
    rating: 4.3,
    time: "35 mins",
    offer: "Buy 1 get 1 free on selected pastas",
    items: [
      { id: 103, name: "Pasta Puttanesca", price: 14.25 },
      { id: 119, name: "Spaghetti Carbonara", price: 13.5 },
      { id: 120, name: "Lasagna", price: 15.0 },
      { id: 121, name: "Fettuccine Alfredo", price: 13.75 },
      { id: 122, name: "Garlic Bread", price: 4.5 },
    ],
  },
  {
    id: 4,
    name: "Taco Town",
    cuisines: ["Mexican"],
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092",
    rating: 3.1,
    time: "20 mins",
    offer: "15% off for first-time customers",
    items: [
      { id: 104, name: "Beef Tacos", price: 9.75 },
      { id: 123, name: "Chicken Quesadilla", price: 8.99 },
      { id: 124, name: "Nachos Supreme", price: 7.5 },
      { id: 125, name: "Guacamole Dip", price: 5.25 },
      { id: 126, name: "Churros", price: 4.0 },
    ],
  },
  {
    id: 5,
    name: "Burger Barn",
    cuisines: ["American", "Fast Food"],
    image: "https://images.unsplash.com/photo-1550317138-10000687a72b",
    rating: 4.2,
    time: "18 mins",
    offer: "Free fries with every burger",
    items: [
      { id: 105, name: "Cheeseburger", price: 7.5 },
      { id: 127, name: "Double Bacon Burger", price: 9.25 },
      { id: 128, name: "Crispy Chicken Sandwich", price: 8.75 },
      { id: 129, name: "Onion Rings", price: 3.5 },
      { id: 130, name: "Milkshake", price: 4.5 },
    ],
  },
  {
    id: 6,
    name: "Noodle Nest",
    cuisines: ["Chinese", "Asian"],
    image:
      "https://static.vecteezy.com/system/resources/previews/016/785/625/large_2x/delicious-noodles-fast-food-meal-with-appetizing-pasta-and-chopsticks-free-photo.jpg",
    rating: 4.1,
    time: "22 mins",
    offer: "10% off on all noodles",
    items: [
      { id: 106, name: "Chow Mein", price: 11.0 },
      { id: 131, name: "Schezwan Noodles", price: 12.25 },
      { id: 132, name: "Spring Rolls", price: 6.75 },
      { id: 133, name: "Fried Rice", price: 10.0 },
      { id: 134, name: "Hot and Sour Soup", price: 5.25 },
    ],
  },
  {
    id: 7,
    name: "Green Garden",
    cuisines: ["Vegan", "Healthy"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    rating: 4.6,
    time: "28 mins",
    offer: "Free smoothie with orders over $25",
    items: [
      { id: 107, name: "Vegan Buddha Bowl", price: 13.45 },
      { id: 135, name: "Quinoa Salad", price: 10.5 },
      { id: 136, name: "Tofu Stir Fry", price: 12.0 },
      { id: 137, name: "Avocado Toast", price: 8.25 },
      { id: 138, name: "Green Smoothie", price: 6.0 },
    ],
  },
  {
    id: 8,
    name: "Curry Kingdom",
    cuisines: ["Indian", "Thai"],
    image:
      "https://as2.ftcdn.net/v2/jpg/01/46/57/47/1000_F_146574709_rUYmeFUbuKlCN0Ex0vhwdYHxzfHKbpaI.jpg",
    rating: 4.4,
    time: "32 mins",
    offer: "Combo meals starting at $9.99",
    items: [
      { id: 108, name: "Chicken Curry with Rice", price: 12.75 },
      { id: 139, name: "Thai Green Curry", price: 11.95 },
      { id: 140, name: "Palak Paneer", price: 10.99 },
      { id: 141, name: "Steamed Rice", price: 2.5 },
      { id: 142, name: "Roti", price: 1.75 },
    ],
  },
  {
    id: 9,
    name: "Pizza Plaza",
    cuisines: ["Italian", "Pizza"],
    image:
      "https://th.bing.com/th/id/OIP.TEen-qtYbRQu7gIQuN0VvwHaFw?rs=1&pid=ImgDetMain",
    rating: 3.9,
    time: "27 mins",
    offer: "2 large pizzas for $20",
    items: [
      { id: 109, name: "Supreme Pizza", price: 16.0 },
      { id: 143, name: "Margherita Pizza", price: 12.0 },
      { id: 144, name: "Pepperoni Pizza", price: 14.5 },
      { id: 145, name: "Garlic Breadsticks", price: 5.0 },
      { id: 146, name: "Chocolate Lava Cake", price: 6.0 },
    ],
  },
  {
    id: 10,
    name: "Middle Feast",
    cuisines: ["Middle Eastern", "Grill"],
    image:
      "https://th.bing.com/th/id/OIP.bhO8Tnn20ljBQ9fxf3b7VQHaFj?rs=1&pid=ImgDetMain",
    rating: 4.3,
    time: "30 mins",
    offer: "Free dessert with orders above $40",
    items: [
      { id: 110, name: "Shish Kebab", price: 15.25 },
      { id: 147, name: "Falafel Wrap", price: 9.5 },
      { id: 148, name: "Hummus & Pita", price: 7.25 },
      { id: 149, name: "Chicken Shawarma", price: 13.0 },
      { id: 150, name: "Baklava", price: 4.75 },
    ],
  },
  {
    id: 11,
    name: "Wrap & Roll",
    cuisines: ["Street Food", "Fast Food"],
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90",
    rating: 4.0,
    time: "15 mins",
    offer: "10% off on combos",
    items: [
      { id: 151, name: "Veg Frankie", price: 5.5 },
      { id: 152, name: "Chicken Roll", price: 6.75 },
      { id: 153, name: "Egg Wrap", price: 5.25 },
      { id: 154, name: "Cheese Corn Roll", price: 6.0 },
      { id: 155, name: "Mayo Paneer Wrap", price: 6.5 },
    ],
  },
  {
    id: 12,
    name: "Sweet Tooth",
    cuisines: ["Desserts", "Bakery"],
    image:
      "https://tb-static.uber.com/prod/image-proc/processed_images/ac4ab3a02e5517c7b9042a6154a5be4a/30be7d11a3ed6f6183354d1933fbb6c7.jpeg",
    rating: 4.8,
    time: "20 mins",
    offer: "Buy 2 pastries, get 1 free",
    items: [
      { id: 156, name: "Chocolate Truffle", price: 3.5 },
      { id: 157, name: "Red Velvet Cake", price: 4.25 },
      { id: 158, name: "Blueberry Muffin", price: 2.75 },
      { id: 159, name: "Vanilla Cupcake", price: 2.5 },
      { id: 160, name: "Macarons Box", price: 6.0 },
    ],
  },
  {
    id: 13,
    name: "Coffee Corner",
    cuisines: ["Cafe", "Beverages"],
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/025/282/026/small/stock-of-mix-a-cup-coffee-latte-more-motive-top-view-foodgraphy-generative-ai-photo.jpg",
    rating: 4.5,
    time: "12 mins",
    offer: "Free cookie with large coffee",
    items: [
      { id: 161, name: "Cappuccino", price: 3.75 },
      { id: 162, name: "Iced Latte", price: 4.0 },
      { id: 163, name: "Espresso Shot", price: 2.5 },
      { id: 164, name: "Cold Brew", price: 4.25 },
      { id: 165, name: "Chocolate Chip Cookie", price: 1.5 },
    ],
  },
  {
    id: 14,
    name: "Waffle Works",
    cuisines: ["Desserts", "Snacks"],
    image:
      "https://www.allrecipes.com/thmb/imrP1HYi5pu7j1en1_TI-Kcnzt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20513-classic-waffles-mfs-025-4x3-81c0f0ace44d480ca69dd5f2c949731a.jpg",
    rating: 4.4,
    time: "18 mins",
    offer: "Flat 20% off on waffle combos",
    items: [
      { id: 166, name: "Nutella Waffle", price: 5.75 },
      { id: 167, name: "Strawberry Delight", price: 6.0 },
      { id: 168, name: "Banana Caramel", price: 5.5 },
      { id: 169, name: "Choco Chip Waffle", price: 5.25 },
      { id: 170, name: "Vanilla Ice Cream Waffle", price: 6.25 },
    ],
  },
  {
    id: 15,
    name: "Biryani Bazaar",
    cuisines: ["Indian", "Biryani"],
    image:
      "https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Chicken-Biryani-Recipe.jpg",
    rating: 4.6,
    time: "35 mins",
    offer: "Family packs starting at $19.99",
    items: [
      { id: 171, name: "Hyderabadi Chicken Biryani", price: 13.99 },
      { id: 172, name: "Veg Biryani", price: 10.75 },
      { id: 173, name: "Mutton Biryani", price: 15.5 },
      { id: 174, name: "Egg Biryani", price: 11.25 },
      { id: 175, name: "Raita & Salad", price: 3.0 },
    ],
  },
  {
    id: 16,
    name: "Sizzling Sizzlers",
    cuisines: ["Grill", "Steakhouse"],
    image:
      "https://www.shutterstock.com/image-photo/paneer-sizzler-indian-version-cottage-600nw-2216735423.jpg",
    rating: 4.2,
    time: "40 mins",
    offer: "Free drink with sizzler",
    items: [
      { id: 176, name: "Chicken Sizzler", price: 15.5 },
      { id: 177, name: "Veg Sizzler", price: 13.0 },
      { id: 178, name: "Beef Steak", price: 18.0 },
      { id: 179, name: "Grilled Vegetables", price: 7.5 },
      { id: 180, name: "Lemonade", price: 2.5 },
    ],
  },
  {
    id: 17,
    name: "The Pancake Hub",
    cuisines: ["Breakfast", "Desserts"],
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0",
    rating: 4.7,
    time: "22 mins",
    offer: "Buy 1 get 1 free pancakes",
    items: [
      { id: 181, name: "Blueberry Pancakes", price: 6.25 },
      { id: 182, name: "Banana Pancakes", price: 5.75 },
      { id: 183, name: "Nutella Stack", price: 7.5 },
      { id: 184, name: "Classic Maple Syrup", price: 5.5 },
      { id: 185, name: "Whipped Cream", price: 1.0 },
    ],
  },
  {
    id: 18,
    name: "The Dosa Den",
    cuisines: ["South Indian"],
    image:
      "https://indiaforbeginners.com/wp-content/uploads/2020/04/India-for-Beginners-custom-tours-8.jpg",
    rating: 4.4,
    time: "30 mins",
    offer: "10% off on orders above $20",
    items: [
      { id: 186, name: "Masala Dosa", price: 6.75 },
      { id: 187, name: "Plain Dosa", price: 5.5 },
      { id: 188, name: "Mysore Dosa", price: 7.25 },
      { id: 189, name: "Rava Dosa", price: 6.0 },
      { id: 190, name: "Coconut Chutney", price: 1.5 },
    ],
  },
  {
    id: 19,
    name: "Tandoori Tadka",
    cuisines: ["Indian", "Tandoori"],
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/041/953/260/small/ai-generated-delicious-chicken-skewers-on-a-slate-platter-with-a-green-dip-and-parsley-in-the-background-photo.jpg",
    rating: 4.1,
    time: "35 mins",
    offer: "15% off on tandoori platters",
    items: [
      { id: 191, name: "Tandoori Chicken", price: 12.5 },
      { id: 192, name: "Paneer Tikka", price: 9.75 },
      { id: 193, name: "Chicken Tikka", price: 11.25 },
      { id: 194, name: "Tandoori Roti", price: 2.0 },
      { id: 195, name: "Mint Chutney", price: 1.0 },
    ],
  },
  {
    id: 20,
    name: "Salad Stop",
    cuisines: ["Healthy", "Vegan"],
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2FsYWR8ZW58MHx8MHx8fDA%3D",
    rating: 4.8,
    time: "18 mins",
    offer: "Free juice with 2 salads",
    items: [
      { id: 196, name: "Caesar Salad", price: 7.25 },
      { id: 197, name: "Kale & Quinoa", price: 8.0 },
      { id: 198, name: "Greek Salad", price: 7.5 },
      { id: 199, name: "Fruit Bowl", price: 6.5 },
      { id: 200, name: "Orange Juice", price: 3.25 },
    ],
  },
  {
    id: 21,
    name: "Ramen Republic",
    cuisines: ["Japanese", "Noodles"],
    image:
      "https://hips.hearstapps.com/hmg-prod/images/birriaramen2-1664194907.jpg",
    rating: 4.3,
    time: "28 mins",
    offer: "Free egg topping on any ramen",
    items: [
      { id: 201, name: "Tonkotsu Ramen", price: 13.25 },
      { id: 202, name: "Shoyu Ramen", price: 12.5 },
      { id: 203, name: "Spicy Miso Ramen", price: 14.0 },
      { id: 204, name: "Veg Ramen", price: 11.75 },
      { id: 205, name: "Egg Add-on", price: 1.25 },
    ],
  },
  {
    id: 22,
    name: "Kathi Junction",
    cuisines: ["North Indian", "Rolls"],
    image:
      "https://images.news18.com/ibnlive/uploads/2023/07/mutton-seekh-kebab-169030200216x9.jpg?impolicy=website&width=640&height=360",
    rating: 4.0,
    time: "20 mins",
    offer: "Flat ₹30 off on ₹300+",
    items: [
      { id: 206, name: "Paneer Kathi Roll", price: 6.75 },
      { id: 207, name: "Chicken Kathi Roll", price: 7.5 },
      { id: 208, name: "Double Egg Roll", price: 5.5 },
      { id: 209, name: "Mutton Seekh Roll", price: 8.25 },
      { id: 210, name: "Chilli Sauce Dip", price: 1.0 },
    ],
  },
  {
    id: 23,
    name: "The Juice Bar",
    cuisines: ["Beverages", "Healthy"],
    image:
      "https://images.pexels.com/photos/16557598/pexels-photo-16557598/free-photo-of-fresh-juice-in-a-glass-and-fruits.jpeg",
    rating: 4.9,
    time: "15 mins",
    offer: "20% off on fresh juices",
    items: [
      { id: 211, name: "Mango Smoothie", price: 4.5 },
      { id: 212, name: "Green Detox", price: 5.25 },
      { id: 213, name: "Berry Blast", price: 5.75 },
      { id: 214, name: "Carrot-Orange Juice", price: 4.0 },
      { id: 215, name: "Beetroot Blend", price: 4.5 },
    ],
  },
  {
    id: 24,
    name: "Shakes & More",
    cuisines: ["Beverages", "Desserts"],
    image: "https://images.deliveryhero.io/image/fd-pk/LH/kbt6-listing.jpg",
    rating: 4.2,
    time: "14 mins",
    offer: "Buy 1 Get 1 on all shakes",
    items: [
      { id: 216, name: "Chocolate Shake", price: 5.25 },
      { id: 217, name: "Strawberry Shake", price: 5.0 },
      { id: 218, name: "Mango Shake", price: 5.0 },
      { id: 219, name: "Oreo Shake", price: 5.5 },
      { id: 220, name: "Vanilla Ice Cream", price: 2.75 },
    ],
  },
  {
    id: 25,
    name: "Momo Magic",
    cuisines: ["Tibetan", "Snacks"],
    image:
      "https://www.cookclickndevour.com/wp-content/uploads/2016/11/whole-wheat-momos-recipe-2.jpg",
    rating: 3.8,
    time: "16 mins",
    offer: "Extra chutney free",
    items: [
      { id: 221, name: "Chicken Momos", price: 6.25 },
      { id: 222, name: "Veg Momos", price: 5.5 },
      { id: 223, name: "Fried Momos", price: 6.75 },
      { id: 224, name: "Cheese Corn Momos", price: 7.0 },
      { id: 225, name: "Spicy Chutney", price: 1.0 },
    ],
  },
  {
    id: 26,
    name: "Cheesy Slice",
    cuisines: ["Pizza", "Italian"],
    image:
      "https://media.istockphoto.com/id/1442417585/photo/person-getting-a-piece-of-cheesy-pepperoni-pizza.jpg?s=612x612&w=0&k=20&c=k60TjxKIOIxJpd4F4yLMVjsniB4W1BpEV4Mi_nb4uJU=",
    rating: 4.3,
    time: "24 mins",
    offer: "2 medium pizzas @ ₹299",
    items: [
      { id: 226, name: "Farmhouse Pizza", price: 11.0 },
      { id: 227, name: "Cheese Burst", price: 12.5 },
      { id: 228, name: "BBQ Chicken Pizza", price: 13.75 },
      { id: 229, name: "Peri Peri Paneer", price: 12.0 },
      { id: 230, name: "Stuffed Crust Add-on", price: 2.0 },
    ],
  },
  {
    id: 27,
    name: "Fish & Chips Co.",
    cuisines: ["Seafood", "British"],
    image:
      "https://media.istockphoto.com/id/855749956/photo/roasted-sea-bream-fish-with-lemon-slices.jpg?s=612x612&w=0&k=20&c=nQhzbjXPnpBDexnk3oK-lU_twHhdTC5R2MixllKbHXE=",
    rating: 4.1,
    time: "32 mins",
    offer: "Combo at $10.99",
    items: [
      { id: 231, name: "Classic Fish & Chips", price: 10.5 },
      { id: 232, name: "Grilled Salmon", price: 13.0 },
      { id: 233, name: "Fish Fingers", price: 7.25 },
      { id: 234, name: "Tartar Sauce", price: 1.25 },
      { id: 235, name: "Mashed Peas", price: 2.0 },
    ],
  },
  {
    id: 28,
    name: "Chaat Central",
    cuisines: ["Indian", "Street Food"],
    image:
      "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/osmvyopiruxry7gksjbz",
    rating: 4.0,
    time: "18 mins",
    offer: "₹50 off on orders ₹300+",
    items: [
      { id: 236, name: "Pani Puri", price: 4.0 },
      { id: 237, name: "Aloo Tikki Chaat", price: 5.25 },
      { id: 238, name: "Dahi Bhalla", price: 4.75 },
      { id: 239, name: "Sev Puri", price: 4.5 },
      { id: 240, name: "Chole Kulche", price: 6.0 },
    ],
  },
  {
    id: 29,
    name: "Toast & Tea",
    cuisines: ["Breakfast", "Cafe"],
    image:
      "https://recipesblob.blob.core.windows.net/assets/b40fb1b592234baebb18e8ed44c5e23e/1272x764/panettone-french-toast.jpg",
    rating: 4.5,
    time: "20 mins",
    offer: "Combo under ₹199",
    items: [
      { id: 241, name: "Buttered Toast", price: 3.0 },
      { id: 242, name: "Masala Chai", price: 2.5 },
      { id: 243, name: "Egg Sandwich", price: 4.75 },
      { id: 244, name: "Veg Cutlet", price: 3.5 },
      { id: 245, name: "Coffee", price: 2.25 },
    ],
  },
  {
    id: 30,
    name: "Grill King",
    cuisines: ["Barbecue", "American"],
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    rating: 4.6,
    time: "34 mins",
    offer: "Free garlic bread with BBQ combo",
    items: [
      { id: 246, name: "BBQ Chicken Wings", price: 10.75 },
      { id: 247, name: "Grilled Corn", price: 4.5 },
      { id: 248, name: "Pulled Sandwich", price: 11.25 },
      { id: 249, name: "Smoked Brisket", price: 13.5 },
      { id: 250, name: "Garlic Bread", price: 3.0 },
    ],
  },
];

module.exports = data;
